   name: sync-lib

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
    unit_test:
      runs-on: ubuntu-latest
      steps:
      - name: go action
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.2'
      - name: checkout repo
        uses: actions/checkout@v2
      - name: test application
        run: make test